stager/urls.py
""" urls.py """
from django.conf.urls.defaults import patterns, url, include
from django.contrib import admin
from django.conf import settings
admin.autodiscover()

handler404 = 'stager.staging.views.error'
handler500 = 'stager.staging.views.error'

urlpatterns = patterns('',
    url(r'^admin/export/', include('stager.export.urls')),
)

urlpatterns += patterns('stager.jira.views',
    (r'^^client/(?P<client_path>.*)/(?P<project_path>.*)/jira/projects/$', 'list_projects'),
    (r'^^client/(?P<client_path>.*)/(?P<project_path>.*)/jira/(?P<jira_key>.*)/add/$', 'insert_issue'),
    (r'^^client/(?P<client_path>.*)/(?P<project_path>.*)/jira/(?P<jira_key>.*)/$', 'view_project'),

)

urlpatterns += patterns('stager.staging.views',
    (r'^home/$','home'),

    (r'^accounts/login/$','login'),
    (r'^login/$','login'),
    (r'^logout/$','logout'),
    
    (r'^admin/(.*)', admin.site.root),

    # Protect assets (make sure apache does not serve this directory)
    (r'^static/'+settings.FILE_UPLOAD+'(?P<filename>.*)$', 'servefile'),

    (r'^$', 'home'),

    (r'^client/(.*)/(.*)/comps/(?P<comp_id>\w+)/$', 'comp_viewer'),
    (r'^client/(.*)/(.*)/comps/(?P<comp_id>\w+)/(?P<idx>\d+)/$', 'comp_viewer'),
    (r'^client/(?P<client_path>.*)/(?P<project_path>.*)/$', 'project'),
    (r'^client/(?P<client_path>\w+)/$', 'client_projects'),
    (r'(?P<client_path>\w+)/$',  'client_projects'),
)



if settings.DEBUG:
    urlpatterns += patterns('django.views.static',
        (r'^static/(.*)$','serve',{'document_root':settings.MEDIA_ROOT}),
    )

stager/jira/models.py
from django.db import models
from stager.staging.models import *

class JiraProject(models.Model):
    key = models.CharField(max_length=128)
    name = models.CharField(max_length=255)
    filter_id = models.CharField(max_length=255)
    updated = models.IntegerField(default=0)
    
    def __unicode__(self):
        return self.name
    
class JiraStatus(models.Model):
    key = models.CharField(max_length=128)
    name = models.CharField(max_length=255)
    updated = models.IntegerField(default=0)
    
    def __unicode__(self):
        return self.name
    
class JiraType(models.Model):
    key = models.CharField(max_length=128)
    name = models.CharField(max_length=255)
    updated = models.IntegerField(default=0)
    allowed = models.BooleanField(default=False)
    
    def __unicode__(self):
        return self.name

class ProjectLink(models.Model):
    ClientProject = models.ForeignKey(Project, unique=True)
    JiraProject = models.ManyToManyField(JiraProject)
   
    def __unicode__(self):
        return self.ClientProject.name

stager/staging/models.py
from django.db import models
from django.conf import settings
from django.contrib.auth.models import User
from django.template.defaultfilters import slugify
import os
from stager.widgets import ColorPickerWidget

class ColorField(models.CharField):
    def __init__(self, *args, **kwargs):
        kwargs['max_length'] = 10
        super(ColorField, self).__init__(*args, **kwargs)

    def formfield(self, **kwargs):
        kwargs['widget'] = ColorPickerWidget
        return super(ColorField, self).formfield(**kwargs)

def get_comp_path(instance, filename):
    return settings.FILE_UPLOAD + "/" + \
        instance.project.client.path + "/" + \
        instance.project.path + "/comps/" + filename

def get_slide_path(instance, filename):
    return settings.FILE_UPLOAD + "/" + \
        instance.comp.project.client.path + "/" + \
        instance.comp.project.path + "/comps/" + filename

def get_logo_path(instance, filename):
    return settings.FILE_UPLOAD + "/" + instance.path + "/" + filename

def get_link_path(instance, filename):
    return settings.FILE_UPLOAD + "/" + \
        instance.project.project.client.path + "/" + \
        instance.project.project.path + filename

class Client(models.Model):
    """
    A client.
    """
    name = models.CharField(max_length=100)
    active = models.BooleanField(default=True)
    path = models.CharField('URL fragment', 
        help_text='<a href="' + settings.BASE_URL + 'url_fragment/" \
                   target="_new" id="url_fragment">' + settings.BASE_URL + 'url_fragment/</a>', max_length=100, unique=True)
    logo = models.ImageField(upload_to=get_logo_path, help_text="( Width = 200, Height = 55 )", blank=True, null=True)
    user = models.ForeignKey(User,related_name='users')
    contact = models.ForeignKey('Contact', related_name='clients',  blank=True, null=True, 
        help_text='The PM. (shows up on the internal homepage)')

    def __unicode__(self):
        return self.name
    
    @property
    def has_multiple_projects(self):
        """
        Returns true if there is more than one active project associated with this client.
        """
        return self.projects.filter(active=True).count() > 1
    
    @property
    def active_projects(self):
        """
        Returns the active projects for the client.
        """
        return self.projects.filter(active=True)
        
    def link(self):
        return "/" + self.path + "/"

class Container(models.Model):
    name = models.CharField(blank=False, max_length=100)
    description = models.TextField(blank=True)
    active = models.BooleanField(default=True)
    
    def __unicode__(self):
        return self.name
    
class Project(Container):
    """
    A project.
    """
    client = models.ForeignKey(Client, related_name='projects')
    path = models.CharField('URL fragment',
        help_text=settings.BASE_URL + 'client/url_fragment/', max_length=100)
    
    def __unicode__(self):
        return '%s - %s' % (self.client.name,self.name)
    
    @property
    def ai_contacts(self):
        return self.contacts.filter(ai_staff=True).filter(active=True)
    
    @property
    def client_contacts(self):
        return self.contacts.filter(ai_staff=False).filter(active=True)
    
    @property
    def active_sections(self):
        return self.sections.filter(active=True).order_by('-date')
    
    @property
    def category_rollups(self):
        return [CategoryRollup(category,self.active_sections.filter(category=category)) for category in self.categories.all()]

    @property
    def link(self):
        return "/clients/" # + self.client.path + "/" + self.path + "/"

    @property
    def default_category(self):
        try: 
            return slugify(self.categories.filter(project=self).filter(default=True)[:1][0].name)
        except:
            try:
                return  slugify(self.categories.filter(project=self)[:1][0].name)
            except:
                return 0

class Contact(models.Model):
    """
    A contact on the project.
    """
    first_name = models.CharField(blank=True, max_length=100)
    last_name = models.CharField(blank=True, max_length=100)
    telephone = models.CharField(blank=True, max_length=100)
    title = models.CharField(blank=True, max_length=100)
    email = models.EmailField()
    projects = models.ManyToManyField(Project,related_name='contacts')
    active = models.BooleanField(default=True)
    ai_staff = models.BooleanField()
    ordering = models.IntegerField(default=0)

    def __unicode__(self):
        return '%s %s' % (self.first_name,self.last_name)

    class Meta:
        ordering = ['ordering']

class Category(models.Model):
    """
    A category of info for a project.
    """
    name = models.CharField(max_length=100)
    project = models.ForeignKey(Project,related_name='categories')
    ordering = models.IntegerField(default=0)
    active = models.BooleanField(default=True)
    default = models.BooleanField(default=False)

    def __unicode__(self):
        return '%s : %s' % (self.project.id, self.name, )

    def save(self, force_insert=False, force_update=False):
        if self.default:
          Category.objects.filter(project=self.project).update(default=None)
        super(Category, self).save(force_insert, force_update)

    class Meta:
        ordering = ['ordering']
        verbose_name_plural = 'categories'


class Section(Container):
    """
    A section of a project.
    """
    project = models.ForeignKey(Project,related_name='sections')
    date = models.DateField(auto_now_add=False)
    category = models.ForeignKey(Category)

    def __unicode__(self):
        return self.name
    
    @property
    def active_links(self):
        return self.links.filter(active=True)
    
    @property
    def active_subsections(self):
        return self.subsections.filter(active=True)

    class Meta:
        ordering = ['date']

class Subsection(Container):
    """
    A subsection of a section.
    """
    section = models.ForeignKey(Container,related_name='subsections')
    
    def __unicode__(self):
        return self.name
    
    @property
    def active_links(self):
        return  self.links.filter(active=True)
    

class Link(models.Model):
    """
    A link to a file.
    """
    remote_link = models.URLField(blank=True, null=True, verify_exists=False)
    file_link = models.FileField(upload_to=get_link_path,blank=True,null=True)
    linked = models.ForeignKey(Container, related_name="links", blank=False, null=False)
    name = models.CharField(blank=True, max_length=100)
    active = models.BooleanField(default=True)
    ordering = models.IntegerField(default=0)
    
    def __unicode__(self):
        return self.name
    
    @property
    def link(self):
        if self.file_link:
            return '%s%s' % (settings.MEDIA_URL, self.file_link)
        else:
            return self.remote_link

    @property
    def project(self):
        try:
            return self.linked.section.section.project
        except:
            try:
                return self.linked.subsection.section.section.project
            except:
                return self.linked.project

    class Meta:
        ordering = ['ordering', ]

        
        
class Comp(models.Model):
    """
    A Link to a comp
    """
    name = models.CharField(max_length=128)
    background = models.ImageField(upload_to=get_comp_path, blank=True, null=True)
    remove_background = models.BooleanField('Remove Background')
    background_colorfield = ColorField(blank=True) 
    ordering = models.IntegerField(default=0)
    active = models.BooleanField(default=True)
    linked = models.ForeignKey(Container, related_name="comps", blank=False, null=False)
    
    @property
    def link(self):
        project = self.project
        return '/client/%s/%s/comps/%s/' % (project.client.path, project.path, self.id )

    @property
    def project(self):
        try:
            return self.linked.section.section.project
        except:
            try:
                return self.linked.subsection.section.section.project
            except:
                return self.linked.project
    
    @property
    def category(self):
        try:
            return self.linked.section.category.name
        except:
            return self.linked.subsection.section.section.category.name
    
    @property
    def returnlink(self):
        project = self.project
        return '/client/%s/%s/#%s_category' % (project.client.path, 
                                               project.path, 
                                               slugify(self.category))
    def __unicode__(self):
        return self.name
        
    def save(self):
        if self.remove_background and self.background != "" and self.background:
            if os.path.exists(self.background.path):
                os.remove(self.background.path)
            self.background = ""
        self.remove_background = False
                
        super(Comp, self).save()

    class Meta:
        ordering = ['ordering', ]

    
class CompSlide(models.Model):
    ALIGNMENT_CHOICES = (
        ('left','left'),
        ('right','right'),
    )
    name = models.CharField(max_length=128)
    comp = models.ForeignKey(Comp, related_name="slides")
    image = models.ImageField(upload_to=get_slide_path, blank=True, null=True)
    alignment = models.CharField(max_length=128, choices=ALIGNMENT_CHOICES, blank=True, null=True)
    backgroundfield = models.ImageField(upload_to=get_slide_path, blank=True, null=True)
    remove_background = models.BooleanField('Remove Background')
    background_colorfield = ColorField(blank=True) 
    active = models.BooleanField(default=True)
    ordering = models.IntegerField(default=0)
    
    @property
    def background(self):
        return self.backgroundfield or self.comp.background or None

    @property
    def background_color(self):

stager/jira/forms.py
from django import forms
from stager.jira.models import *
from django.utils.functional import lazy


def type_choices():
    return [(type.key, type.name) for type in JiraType.objects.filter(allowed=True)]

class JiraTicketForm(forms.Form):
    def __init__(self, *args, **kwargs):
        super(JiraTicketForm, self).__init__(*args, **kwargs)
        self.fields['issue_type'] = forms.ChoiceField(choices=type_choices())
        self.fields['description'] = forms.CharField(widget=forms.Textarea)
        self.fields['steps_to_reproduce'] = forms.CharField(widget=forms.Textarea)
        self.fields['attachment'] = forms.FileField(required=False)
    summary = forms.CharField(widget=forms.Textarea)

#choices=[('bug', 'Bug'),
#          ('feature', 'New Feature')])

templates/jira/jira_create_issue.html
{% extends "base.html" %}

{% block page_title %} 
	Clients : Projects
{% endblock %}

{% block cufon %}
	Cufon.replace('#maincontent .content h2', { fontFamily: 'Berthold Akzidenz Grotesk BE CN' });
	Cufon.replace('#sidebar h3', { fontFamily: 'Berthold Akzidenz Grotesk BE CN' });
{% endblock %}

{% block section_css %}
	<link href="{{ MEDIA_URL }}/static/css/jira/jira_table.css" rel="stylesheet" type="text/css" />
{% endblock %}

{% block section_js %}
	<script type="text/javascript" src="{{ MEDIA_URL }}/static/js/dropdown.js"></script>
	<script type="text/javascript" src="{{ MEDIA_URL }}/static/js/staging.js"></script>
{% endblock %}

{% block title %}{{ client.name }} {% endblock %}
{% block description %}{{ project.name }} {% endblock %}

{% block utility %}
	{% include "includes/nav_utility.html" %}
{% endblock %}

{% block header_extra %}
	{% include "includes/header.html" %}
{% endblock %}

{% block main_content %}
<div id="main" class="clear">
	<div id="maincontent">
		{% if client %}
			<div class="content">
				<div class="projects jira">
					<div class="head">
						<h2 class="projects">{{ jira_project.name }} - Create Issue</h2>
					</div>
					{% if issue_url %}
					<div class="thank_you">
						<h3>Thank you. Created Issue: {{ issue_url }}</h3><br/>
						<a href="/client/{{ client_path }}/{{ project_path }}/jira/{{ jira_project.key }}" class="return clear">Return to Jira Project</a><br /> 
						<a href="/client/{{ client_path }}/{{ project_path }}/jira/{{ jira_project.key }}/add">Add another issue</a>
					</div>
					{% else %}
						<div id="jira_form_wrapper">
							<form id="jiraform" enctype="multipart/form-data" action="." method="POST">
								<!--{{ form.as_p }}-->
								<fieldset>
									{% if form.summary.errors %}{{ form.summary.errors }}{% endif %}
									<label for="id_summary">Summary:</label>
									{{ form.summary }}
								</fieldset>
								<fieldset>
									{% if form.issue_type.errors %}{{ form.issue_type.errors }}{% endif %}
									<label for="id_issue_type">Issue type:</label>
									{{ form.issue_type }}
								</fieldset>
								<fieldset>
									{% if form.description.errors %}{{ form.description.errors }}{% endif %}
									<label for="id_description">Description:</label>
									{{ form.description }}
								</fieldset>
								<fieldset>
									{% if form.steps_to_reproduce.errors %}{{ form.steps_to_reproduce.errors }}{% endif %}
									<label for="id_steps_to_reproduce">Steps to reproduce:</label>
									{{ form.steps_to_reproduce }}
								</fieldset>
								<fieldset>
									{% if form.attachment.errors %}{{ form.attachment.errors }}{% endif %}
									<label for="id_attachment">Attachment:</label>
									{{ form.attachment }}
								</fieldset>	
								<fieldset>
									<input type="submit" value="Submit" id="jiraformsubmit" class="submit" />
									<img src="/static/images/ajax_loader.gif" class="spinner" style="display: none;" />
								</fieldset>
							</form>
						</div>
					{% endif %}
				</div>
			{% endif %}
		</div>
	</div>
</div>

<div id="sidebar">
	{% block project_links %}	
		<div class="contact-list" id="project-links">
			<h3>Project Resources</h3>
			<ul>
				<li><a href="/client/{{ client_path }}/{{ project_path }}/jira/{{ jira_key }}/">{{ jira_key}} Home</a></li>
				<li><a href="/client/{{ client_path }}/{{ project_path }}/">Project Home</a></li>
				{% if project.links.all %}
				{% for link in project.links.all %}
					<li><a onclick="window.open(this.href);return false;" href="{{ link.link }}" >{{ link.name }}</a>
					</li>
				{% endfor %}
				{% endif %}
			</ul>
		</div>	
	{% if project.ai_contacts %}
		<div class="contact-list" id="ai-contacts">
			<h3>A<span>i</span> Contacts</h3>
			{% for contact in project.ai_contacts %}
				{% include "contact.html" %}
			{% endfor %}
		</div>
	{% endif %}
	{% if project.client_contacts %}
		<div class="contact-list" id="client-contacts">
			<h3>Client Contacts</h3>
			{% for contact in project.client_contacts %}
				{% include "contact.html" %}
			{% endfor %}
		</div>
	{% endif %}
	{% include "includes/info.html" %}
	{% endblock %}
</div>

<script type="text/javascript">
    $('#jiraform').submit(function(){
		$('#jiraformsubmit').attr('disabled', 'disabled');
		$("#jiraform").fadeTo("slow", 0.5);
	});
</script>
{% endblock %}

templates/jira/jira_list_projects.html
{% extends "base.html" %}

{% block page_title %} 
	{{ project.client.name }} : {{ project.name }} : Jira Projects
{% endblock %}

{% block cufon %}
	Cufon.replace('#maincontent .content h2', { fontFamily: 'Berthold Akzidenz Grotesk BE CN' });
	Cufon.replace('#sidebar h3', { fontFamily: 'Berthold Akzidenz Grotesk BE CN' });
{% endblock %}

{% block section_css %}
	<link href="{{ MEDIA_URL }}/static/css/jira/jira_table.css" rel="stylesheet" type="text/css" />
{% endblock %}

{% block section_js %}
		<script type="text/javascript" src="{{ MEDIA_URL }}/static/js/dropdown.js"></script>
		<script type="text/javascript" src="{{ MEDIA_URL }}/static/js/staging.js"></script>
{% endblock %}

{% block title %}{{ client.name }} {% endblock %}
{% block description %}{{ project.name }} {% endblock %}

{% block header_extra %}
	{% include "includes/header.html" %}
{% endblock %}
	
{% block main_content %}
<div id="main" class="clear">
	<div id="maincontent">
		{% if client %}
		<div class="content">
			<div class="projects">
				<div class="head">
					<h2 class="projects clear">Jira Projects</h2>
				</div>
				{% if jiras %}
				<ul class="projects">
					{% for jira in jiras %}
					<li><a href="/client/{{ client.path }}/{{ project.path }}/jira/{{ jira.key}}/">{{ jira.name }}</a></li>
					{% endfor %}
				</ul>
				{% endif %}
			</div>
		{% endif %}
		</div>
	</div>
</div>

<div id="sidebar">
	{% block project_links %}	
		<div class="contact-list" id="project-links">
			<h3>Project Resources</h3>
			<ul>
				<li><a href="/client/{{ client_path }}/{{ project_path }}/">Project Home</a></li>
				{% if project.links.all %}
				{% for link in project.links.all %}
					<li><a onclick="window.open(this.href);return false;" href="{{ link.link }}" >{{ link.name }}</a>
					</li>
				{% endfor %}
				{% endif %}
			</ul>
		</div>	
	{% if project.ai_contacts %}
		<div class="contact-list" id="ai-contacts">
			<h3>A<span>i</span> Contacts</h3>
			{% for contact in project.ai_contacts %}
				{% include "contact.html" %}
			{% endfor %}
		</div>
	{% endif %}
	{% if project.client_contacts %}
		<div class="contact-list" id="client-contacts">
			<h3><img src="{{ MEDIA_URL }}/static/images/title_client-contacts.gif" alt="Client Contacts" /></h3>
			{% for contact in project.client_contacts %}
				{% include "contact.html" %}
			{% endfor %}
		</div>
	{% endif %}
	{% include "includes/info.html" %}
	{% endblock %}
</div>

<!--
Create a User / Client:
<form action="" method="post">
<input type="text" name="username">
<input type="password" name="password">
<input type="submit" value="Create User / Client"
</form>
-->
{% endblock %}

templates/jira/jira_project.html
{% extends "base.html" %}

{% block page_title %} 
	{{ project.client.name }} : {{ project.name }} : Jira Projects
{% endblock %}

{% block section_css %}
		<style type="text/css">
			#maincontent .content {
				padding: 0 1em;
			}
		</style>
<link href="{{ MEDIA_URL }}/static/css/jira/jira_table.css" rel="stylesheet" type="text/css" />
<link href="{{ MEDIA_URL }}/static/css/jquery.fancybox-1.2.5.css" rel="stylesheet" type="text/css" />
{% endblock %}

{% block section_js %}
		<script type="text/javascript" src="{{ MEDIA_URL }}/static/js/grid.locale-en.js"></script>
		<script type="text/javascript" src="{{ MEDIA_URL }}/static/js/jquery.dataTables.js"></script>
		<script type="text/javascript" src="{{ MEDIA_URL }}/static/js/jquery.fancybox-1.2.5.js"></script>
		<script type="text/javascript" src="{{ MEDIA_URL }}/static/js/dropdown.js"></script>
{% endblock %}

{% load issue_status %}
{% block main_content %}
<div id="main" class="clear">
	<div id="content-1">
		{% include "includes/header.html" %}
	</div>
	<div id="maincontent">
		{% if client %}
			<h1>{{ client.name }}</h1>
			<div class="content">
				<div class="projects">
					<div class="head">
						<h2 class="projects">{{ jira_project.name }}</h2>
						<a href="add/" class="create_issue">Create Issue</a>
					</div>
					{% if jiras %}
						<table cellpadding="0" cellspacing="0" border="0" class="display" id="example">
							<thead>
								<tr>
									<th>Issue</th>
									<th>Summary</th>
									<th>Description</th>
									<th>Status</th>
									<th>Version</th>
								</tr>
							</thead>
							<tbody>
								{% for jira in jiras %}
									<tr>
										<td><div class="inline">{{ jira.key }}</div></td>
										<td><a class="inline" href="#{{ jira.id }}">{{ jira.summary }}</a></td>
										<td></td>
										<td><div class="inline">{{ jira.status|status_string }}</div></td>
										<td><div class="inline">{% for v in jira.fixVersions %}{% if forloop.first %}{{ v.name }}{% endif %}{% endfor %}</div></td>
								{% endfor %}
							</tbody>
							<tfoot>
								<tr>
									<th>Issue</th>
									<th>Summary</th>
									<th>Description</th>
									<th>Status</th>
									<th>Version</th>
								</tr>
							</tfoot>
						</table>
					{% endif %}
				</div>
			</div>
		{% endif %}
	</div>
</div>

<div id="sidebar">
	<a id="logout" href="/logout/">Log Out</a>
	<a href="/home/"><img src="{{ MEDIA_URL }}/static/images/logo_ai.gif" alt="Alexander Interactive Staging Site"  title="Alexander Interactive Staging Site" class="ai-logo" width="42" /></a>
	{% block project_links %}
	
		<div class="contact-list" id="project-links">
			<h3><img src="{{ MEDIA_URL }}/static/images/title_project-resources.gif" alt="Project Resources" /></h3>
			<ul>
				<li><a href="/client/{{ client_path }}/{{ project_path }}/">Project Home</a></li>
				{% if project.links.all %}
				{% for link in project.links.all %}
					<li><a onclick="window.open(this.href);return false;" href="{{ link.link }}" >{{ link.name }}</a>
					</li>
				{% endfor %}
				{% endif %}
			</ul>
		</div>
	
	{% if project.ai_contacts %}
		<div class="contact-list" id="ai-contacts">
			<h3><img src="{{ MEDIA_URL }}/static/images/title_ai-contacts.gif" alt="AI Contacts" /></h3>
			{% for contact in project.ai_contacts %}
				{% include "contact.html" %}
			{% endfor %}
		</div>
	{% endif %}
	{% if project.client_contacts %}
		<div class="contact-list" id="client-contacts">
			<h3><img src="{{ MEDIA_URL }}/static/images/title_client-contacts.gif" alt="Client Contacts" /></h3>
			{% for contact in project.client_contacts %}
				{% include "contact.html" %}
			{% endfor %}
		</div>
	{% endif %}
	{% include "includes/info.html" %}
	{% endblock %}
</div>

{% if jiras %}
	{% for jira in jiras %}
		<div style="display:none" id="{{ jira.id }}">
			<div class="wrapper">
			<strong>Issue:</strong>{{ jira.key }}<br/><br/>
			<strong>Status:</strong> {{ jira.status|status_string }}<br/><br/>
			<strong>Summary:</strong> {{ jira.summary }}<br/><br/>
			<strong>Description:</strong> {{ jira.description }}<br/><br/>
			<!-- <strong>PM Status:</strong> {{ jira.customFieldValues }}<br/><br/> -->
			<strong>Versions:</strong> {% for v in jira.fixVersions %}{{ v.name }}{% endfor %}<br/><br/>
			</div>
		</div>
	{% endfor %}
	<script type="text/javascript">
		$(document).ready(function() {
			$('#example').dataTable( {
				"bPaginate": false,
				"bLengthChange": false,
				"bFilter": true,
				"bSort": true,
				"bInfo": false,
				"bAutoWidth": false,
				"aoColumns": [null, { "bSortable": false }, { "bSearchable": false,"bVisible": false }, null, null]
	
			 } );
		 
		 	$("a.inline").fancybox();
		} );
	</script>
{% endif %}
{% endblock %}

templates/jira/project.html
{% extends 'stager/project.html' %}

{% block cufon %}
	Cufon.replace('.lead h2', { fontFamily: 'Berthold Akzidenz Grotesk BE CN' });
	Cufon.replace('.lead .date', { fontFamily: 'Berthold Akzidenz Grotesk BE CN' });
	Cufon.replace('#sidebar h3', { fontFamily: 'Berthold Akzidenz Grotesk BE CN' });
	Cufon.replace('.contentblock p.pm-subcat', { fontFamily: 'Berthold Akzidenz Grotesk BE CN' });
	Cufon.replace('#otherprojects .header', { fontFamily: 'Berthold Akzidenz Grotesk BE CN' });
	Cufon.replace('#maincontent .cat-buttons li', { fontFamily: 'Berthold Akzidenz Grotesk BE CN', hover:true });
	Cufon.replace('.catblock .filter h3', { fontFamily: 'Berthold Akzidenz Grotesk BE CN' });
{% endblock %}

{% block title %}{{ client.name }} {% endblock %}
{% block description %}{{ project.name }} {% endblock %}


{% block header_extra %}
	{% include "includes/header.html" %}
{% endblock %}

{% load has_jira %}
	{% block project_links %}	
	
	{% if project.links.all %}
		<div class="contact-list" id="project-links">
			<h3>Project Resources</h3>
			<ul>
				{% for link in project.links.all %}
					<li class="{{ link.name }}"><a onclick="window.open(this.href);return false;" href="{{ link.link }}">{{ link.name }}</a></li>
				{% endfor %}
				{% if client.path|has_jira:project.path %}
					<li class="jira"><a href="jira/projects">Jira</a></li>
				{% endif %}
			</ul>
		</div>
	{% else %}
		{% if not mobify %}
			{% if client.path|has_jira:project.path %}
			<div class="contact-list" id="project-links">
				<h3>Project Resources</h3>
				<ul>
					<li><a href="jira/projects">Jira</a></li>
				</ul>
			</div>
			{% endif %}
		{% endif %}
	{% endif %}
	{% endblock %}
	